name: permissions_demo
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  # permission_handler: ^3.1.0
  permission: ^0.1.2
  # simple_permissions: ^0.1.9
  # flutter_baidu_map: ^0.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
